# Generated by Django 4.1.5 on 2023-01-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoTask', '0002_rename_config_taskrec_configjson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrec',
            name='executeTimeLimit',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='taskscheme',
            name='executeTimeLimit',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
